version: '3'

services:

  webserver:
    build: .
    container_name: webserver
    ports:
      - "8080:8080"
    
    environment:
      - MYSQL_HOST=10.1.0.2
      - MYSQL_USER=root
      - MYSQL_PASS=secret
      - MYSQL_DBN=abcdb
      - MYSQL_PORT=3306
      
