version: '3'

services:

  db:
    image: 'mysql:latest'
    container_name: mysql_database
    ports:
      - "3306:3306"
    
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=new_database